//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROLINEA
    {
        public AEROLINEA()
        {
            this.AVION = new HashSet<AVION>();
        }
    
        public int idaerolinea { get; set; }
        public string ruc { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<AVION> AVION { get; set; }
    }
}
