//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class AEROPUERTO
    {
        public AEROPUERTO()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public string idaeropuerto { get; set; }
        public string nombre { get; set; }
        public string idpais { get; set; }
    
        public virtual PAIS PAIS { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
