//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIENTO
    {
        public ASIENTO()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public int idasiento { get; set; }
        public string letra { get; set; }
        public int fila { get; set; }
    
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
