//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVION
    {
        public AVION()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public string idavion { get; set; }
        public int idaerolinea { get; set; }
        public string fabricante { get; set; }
        public string tipo { get; set; }
        public int capacidad { get; set; }
    
        public virtual AEROLINEA AEROLINEA { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
