//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBReserva : DbContext
    {
        public DBReserva()
            : base("name=DBReserva")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AEROLINEA> AEROLINEA { get; set; }
        public DbSet<AEROPUERTO> AEROPUERTO { get; set; }
        public DbSet<ASIENTO> ASIENTO { get; set; }
        public DbSet<AVION> AVION { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<PASAJERO> PASAJERO { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TARIFA> TARIFA { get; set; }
        public DbSet<VUELO> VUELO { get; set; }
    }
}
