//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int idpago { get; set; }
        public int idreserva { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string idpasajero { get; set; }
        public decimal monto { get; set; }
        public string tipo_comprobante { get; set; }
        public string num_comprobante { get; set; }
        public decimal impuesto { get; set; }
    
        public virtual PASAJERO PASAJERO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
