//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public PAIS()
        {
            this.AEROPUERTO = new HashSet<AEROPUERTO>();
            this.PASAJERO = new HashSet<PASAJERO>();
        }
    
        public string idpais { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<AEROPUERTO> AEROPUERTO { get; set; }
        public virtual ICollection<PASAJERO> PASAJERO { get; set; }
    }
}
