//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASAJERO
    {
        public PASAJERO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public string idpasajero { get; set; }
        public string nombre { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string idpais { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string clave { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual PAIS PAIS { get; set; }
    }
}
