//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.PAGO = new HashSet<PAGO>();
            this.VUELO = new HashSet<VUELO>();
        }
    
        public int idreserva { get; set; }
        public decimal costo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observacion { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
