//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFA
    {
        public TARIFA()
        {
            this.VUELO = new HashSet<VUELO>();
        }
    
        public int idtarifa { get; set; }
        public string clase { get; set; }
        public decimal precio { get; set; }
        public decimal impuesto { get; set; }
    
        public virtual ICollection<VUELO> VUELO { get; set; }
    }
}
