//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class VUELO
    {
        public int idasiento { get; set; }
        public string idaeropuerto { get; set; }
        public int idreserva { get; set; }
        public string idavion { get; set; }
        public int idtarifa { get; set; }
    
        public virtual AEROPUERTO AEROPUERTO { get; set; }
        public virtual ASIENTO ASIENTO { get; set; }
        public virtual AVION AVION { get; set; }
        public virtual RESERVA RESERVA { get; set; }
        public virtual TARIFA TARIFA { get; set; }
    }
}
